/*
 * #%L
 * LaBoGrid
 * %%
 * Copyright (C) 2011 LaBoGrid Team
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 3 of the 
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public 
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/gpl-3.0.html>.
 * #L%
 */
/**
 * Provides executable tools for converting and producing files linked to
 * LaBoGrid.
 * <p>
 * {@link laboGrid.utils.ConvertIntoASCII ConvertForMatlab}
 * converts binary data files generated by LaBoGrid into text files that can
 * be parsed, for example using a Matlab script. 
 * {@link laboGrid.utils.CompareAsciiFluids CompareAsciiFluids}
 * compares the 2 given states of a lattice.
 * {@link laboGrid.utils.SolidBitmapWriter SolidBitmapWriter}
 * generates solid files.
 */
package laboGrid.utils;
